export const skillIcons = {
  HTML: "devicon-html5-plain colored",
  CSS: "devicon-css3-plain colored",
  JavaScript: "devicon-javascript-plain colored",
  TypeScript: "devicon-typescript-plain colored",
  React: "devicon-react-original colored",
  "Node.js": "devicon-nodejs-plain colored",
  Python: "devicon-python-plain colored",
  AWS: "devicon-amazonwebservices-plain-wordmark colored",
  Docker: "devicon-docker-plain colored",
  Git: "devicon-git-plain colored",
  SQL: "devicon-mysql-plain colored",
  Nextjs: "devicon-nextjs-original colored",
  Tailwindcss: "devicon-tailwindcss-plain colored",
  Websockets: "fa-solid fa-network-wired",
  GraphQL: "devicon-graphql-plain colored",
};
